name: Build OpenAppFilter for OpenWrt 22.03.7

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/openwrt/sdk/x86_64:22.03.7  # 修正后的官方镜像地址
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git subversion build-essential

    - name: Configure feeds
      run: |
        cat << EOF > feeds.conf.default
        src-git packages https://git.openwrt.org/feed/packages.git^openwrt-22.03
        src-git luci https://git.openwrt.org/project/luci.git^openwrt-22.03
        EOF
        
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Prepare package
      run: |
        mkdir -p package/openappfilter
        cp -r $GITHUB_WORKSPACE/* package/openappfilter/

    - name: Compile packages
      run: |
        make defconfig
        make package/openappfilter/compile V=s

    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        find bin -name '*oaf*.ipk' -exec cp {} artifacts/ \;

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-22.03.7-IPKs
        path: artifacts/
