name: Compile OpenAppFilter by doubao

on:
  push:
    branches:
      - main # 监听main分支的推送事件，可根据实际情况修改
  workflow_dispatch: # 支持手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的Ubuntu系统作为运行环境

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # 检出代码到工作目录，使用v4版本

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip wget zlib1g-dev # 安装编译所需的基础依赖

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/22.03.7/targets/x86/64/openwrt-sdk-22.03.7-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xvf openwrt-sdk-22.03.7-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-22.03.7-x86-64_gcc-11.2.0_musl.Linux-x86_64 openwrt-sdk

      - name: Update and install feeds
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy OAF Source Code to SDK
        run: |
          mkdir -p openwrt-sdk/package/OpenAppFilter
          rsync -av --exclude '.git' . openwrt-sdk/package/OpenAppFilter/

      - name: Open Compile Configuration
        run: |
          cd openwrt-sdk
          echo "CONFIG_PACKAGE_luci-app-oaf=y" >>.config  
          make defconfig  # 配置OAF编译选项

      - name: Compile OAF Separately
        run: |
          cd openwrt-sdk
          make package/OpenAppFilter/compile V=s # 编译OpenAppFilter相关组件

      - name: Compile the Entire Firmware (Optional)
        run: |
          cd openwrt-sdk
          make V=s # 编译整个固件，若仅需特定IPK，此步骤可注释掉

      - name: Collect Compiled IPKs
        run: |
          mkdir -p compiled_ipks
          find openwrt-sdk/bin -name "kmod-oaf*.ipk" -exec cp {} compiled_ipks/ \;
          find openwrt-sdk/bin -name "appfilter*.ipk" -exec cp {} compiled_ipks/ \;
          find openwrt-sdk/bin -name "luci-compat*.ipk" -exec cp {} compiled_ipks/ \;
          find openwrt-sdk/bin -name "luci-app-oaf*.ipk" -exec cp {} compiled_ipks/ \;
          find openwrt-sdk/bin -name "luci-i18n-oaf-zh-cn*.ipk" -exec cp {} compiled_ipks/ \;

      - name: Upload Compiled IPKs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-ipks
          path: compiled_ipks # 将编译好的IPK文件作为构建产物上传，方便后续下载使用
